chan/accounts/urls.py
urlpatterns = [

]

chan/blog/urls.py
from django.urls import path  # urlpatterns에 path를 쓰려고 import한 것
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),  # 여기서 name은 이 path의 이름을 의미함
]

chan/chan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    # path('', TemplateView.as_view(template_name='root.html'), name='root'),
    path('', RedirectView.as_view(url='/instagram/'), name='root'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('instagram/', include('instagram.urls')),
]

# 장고는 실제 서비스시에, media나 static파일 serving을 장고 기본으로 하는 것을 권장하지 않음.
# if settings.DEBUG:가 없더라도 DEBUG가 False면 빈 문자열을 반환하지만, 명시적으로 하기 위해서 쓴다.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chan/instagram/urls.py
from django.urls import path
from . import views

app_name = 'instagram'  # URL Reverse에서 namespace역할을 하게 된다.

urlpatterns = [
    path('new/', views.post_new, name='post_new'),
    path('', views.post_list, name='post_list'),
    # path의 name은 get_absolute_url에서 쓰인다.
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('archives/<int:year>/', views.archives_year),
]

chan/accounts/models.py
from django.conf import settings
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=6)

chan/blog/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='+')
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # return f"Custom Post object ({self.id})"
        return "Custom Post object ({})".format(self.id)

chan/instagram/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.core.validators import MinLengthValidator


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # settings.AUTH_USER_MODEL은 기본 유저 모델
    # 1측에 해당하는 pk가 post_id라는 이름으로 저장된다
    message = models.TextField(validators=[MinLengthValidator(10)])
    # blank가 True라는 것은 꼭 사진을 안넣어도 된다는 것
    photo = models.ImageField(blank=True, upload_to='instagram/post/%Y/%m/%d')
    # blank=True로 하면 태그는 필수가 아님
    tag_set = models.ManyToManyField('Tag', blank=True)
    is_public = models.BooleanField(default=False, verbose_name='공개여부')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        # return f"Custom Post object ({self.id})"
        # return "Custom Post object ({})".format(self.id)
        return self.message

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args={self.pk})

    # def message_length(self):
    #     return len(self.message)
    # message_length.short_description = "메세지 글자수"


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, limit_choices_to={'is_public': True})  # limit_choices_to 는 is_public이 True인 것만 고를수 있게 해준다.
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

chan/instagram/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

chan/accounts/views.py
from django.shortcuts import render

# Create your views here.

chan/blog/views.py
from django.shortcuts import render
from .models import Post


def post_list(request):
    # qs = Queryset -> 전달받은 객체의 목록, 데이터베이스로부터 데이터를 읽고, 필터를 걸거나 정렬할 수 있음
    qs = Post.objects.all()
    return render(request, 'blog/post_list.html', {
        'post_list': qs,
    })

chan/instagram/views.py
from django.views.generic import ListView, DetailView
from django. http import HttpResponse, HttpRequest, Http404
from django.shortcuts import render, get_object_or_404, render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm

# post_list = login_required(ListView.as_view(model=Post, paginate_by=10))


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = PostForm()

    return render(request, 'instagram/post_form.html', {
        'form': form,
    })


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 10


post_list = PostListView.as_view()

# @login_required
# def post_list(request):
#     # q라는 인자가 있으면 가져오고, 없으면 빈 문자열을 반환해라. 그것을 q에 저장
#     qs = Post.objects.all()
#     # GET인자, 쿼리스트링 인자라고도 하며 url창에 http://127.0.0.1:8000/instagram/?q=내용 이런식으로 쓴다
#     q = request.GET.get('q', '')
#     if q:
#         # filter함수는 특정 조건으로 걸러서 걸러진 요소들로 iterator객체를 만들어서 리턴
#         # message에서 q라는 문자열이 포함된 자료를 찾아서 qs에 저장
#         qs = qs.filter(message__icontains=q)
#     return render(request, 'instagram/post_list.html', {
#         'post_list': qs,
#         'q': q,
#     })


# def post_detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     # @@@@앞의 pk는 필드를 지정한 것이고 뒤의 pk는 값을 넘긴것 만약에 post_detail(request, ab)였다면 pk=ab가 된다.@@@@
#     return render(request, 'instagram/post_detail.html', {
#         'post': post,
#     })

# post_detail = DetailView.as_view(
#     model=Post,
#     queryset = Post.objects.filter(is_public=True))

class PostDetailView(DetailView):
    model = Post

    def get_queryset(self):
        qs = super().get_queryset()
        if not self.request.user.is_authenticated:
            qs = qs.filter(is_public=True)
        return qs


post_detail = PostDetailView.as_view()


def archives_year(request, year):
    return HttpResponse(f"{year}년 archives")

chan/blog/templates/blog/post_list.html
<h1>Post List</h1>

<!-- 여기서 post_list는 blog/views.py에 정의된 것을 말함 -->
<!-- 이 템플릿은 blog/views.py에 render부분에서 활용된다 -->
<!-- 템플릿 변수를 사용하여 html 문서 상에서도 어떠한 객체의 속성들에 접근할 수 있고, 이를 출력할 수 있도록 지원합니다. -->
<!-- 템플릿 태그는 {% %}로 구성되어 있습니다. -->
<!-- HTML 문서는 프로그래밍 언어가 아니고 마크업 언어이기 때문에 단지 문서를 웹에서 띄워주는 역할만 한다.
그렇기 때문에 HTML 자체는 프로그래밍적 로직을 구현할 수 없다. 하지만 템플릿 태그를 사용한다면 가능하다. -->
<!-- {% extends %}와 같이 단독으로 사용할 수 있는 템플릿 태그들도 있지만,
    {% if %} 처럼 뒤에 {% endif %} 템플릿 태그를 반드시 닫아주어야 하는 것들도 있습니다. -->
{% for post in post_list %}
<h2>{{ post.title }}</h2>
{{ post.content }} {% endfor %}

chan/chan/templates/root.html
hi

chan/instagram/templates/instagram/post_detail.html
<h2>Author : {{ post.author }}</h2>

{% if post.photo %}
<img src="{{ post.photo }}" />
{% endif %} {{ post.message }}

chan/instagram/templates/instagram/post_form.html
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token%}
  <table>
    {{ form }}
  </table>
  <input type="submit" value="저장" />
</form>

chan/instagram/templates/instagram/post_list.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8" />
    <title>post list</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <form action="" method="GET">
      <!-- input type의 name에 따라 http://127.0.0.1:8000/instagram/?q= 에서 ?뒤에 오는 이름이 정해진다 지금은 q -->
      <input type="text" name="q" value="{{q}}" />
      <input type="submit" value="검색" />
    </form>
    <a
      href="{% url 'instagram:post_new' %}"
      class="btn btn-primary btn-block mt-3 mb-3"
      >새 포스팅</a
    >

    <table class="table table-borderd table-hover">
      <tbody>
        <!--여기서 쓰인 post_list는 view.py에 post_list 함수에 render부분에 정의한 post_list를 말하는 것임 -->
        {% for post in post_list %}
        <tr>
          <td>{{ post.pk }}</td>
          <td>
            <!-- 만약 if문을 안써주면 photo가 존재하지 않는 글들 때문에 The 'photo' attribute has no file associated with it.라는 오류가
            발생한다. -->
            {% if post.photo %}
            <img src=" {{ post.photo.url }}" style="width: 100px;" /> {% else %}
            NO photo {%endif%}
          </td>
          <td>
            <a href="{{ post.get_absolute_url }}">{{ post.message }}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %} {% bootstrap_pagination page_obj %} {% endif %}
  </body>
</html>
<!-- https://django-bootstrap4.readthedocs.io/en/latest/# 장고 부트스트랩 4 -->